arch: "lffd"
config: "slim"

hparams:
  learning_rate: 0.1
  momentum: 0.9
  weight_decay: 0.00001
  milestones: [500000, 1000000, 1500000]
  gamma: 0.1
  ratio: 10
  image_size: 640

preprocess:
  normalized_input: false
  mean: 127.5
  std: 127.5