arch: "yolov4"
config: "tiny"

hparams:
  learning_rate: 0.001
  momentum: 0.9
  weight_decay: 0.0005
  batch_size: 32
  mini_batch_size: 8
  image_size: 608
  pos_cls_loss_weight: 1
  neg_cls_loss_weight: 1
  reg_loss_weight: 1
  gradient_clip_val: 0
  augmentations:
    brightness: 0.5
    contrast: 0.5
    saturation: 0.5
    degree_range: 30
  step_size: 20
  gamma: 0.1

preprocess:
  normalized_input: true
  mean: [0.4700183096266855, 0.4345199880807893, 0.4083990696176792]
  std: [0.3026302615599824, 0.29266974735666573, 0.29741784465393734]